### ISSUE TITLE
Meter is detected but speed doesn't change for Handy.

### ISSUE THREAD

**Issue by KillMeWithMemes** [Furimanejo/In-Heat#1]
I have everything working (graph is showing meter being read accurately)
However the device isn't changing it's speed at all.
For example, my minimum stroke speed is 10 BPM which is working perfectly, my maximum is 120 BPM and my on-fire meter has gone from 0-100 all while remaining 10 BPM.

**Comment by Furimanejo** [comment]
That's weird. Send me a message at my discord server and I'll help you debug this. https://discord.gg/HhQa5xX9
